### PR TITLE
Fix pagination

### LINKED ISSUE #453: Pagination looks a little off
Screen Shot 2019-10-19 at 12 46 40

### PR DESCRIPTION
**Pull request by joedixon**
Screenshot 2019-12-02 at 20 22 33

Fixes #453

### CODE REVIEW

File: config/database.php [hunk 1]
```diff
@@ -56,7 +56,7 @@
             'collation' => 'utf8mb4_unicode_ci',
             'prefix' => '',
             'prefix_indexes' => true,
-            'strict' => true,
+            'strict' => false,
```
Comment (driesvints) [inline config/database.php]: Can you change this back again? 😅
